.:
  - path: /tsconfig.build.json
    type: file
  - path: /dist
    type: directory
    contents:
    - path: /dist/tsconfig.build.tsbuildinfo
      type: file
    - path: /dist/app.module.js
      type: file
    - path: /dist/students
      type: directory
      contents:
      - path: /dist/students/students.service.js
        type: file
      - path: /dist/students/students.controller.d.ts
        type: file
      - path: /dist/students/entities
        type: directory
        contents:
        - path: /dist/students/entities/student.entity.js
          type: file
        - path: /dist/students/entities/student.entity.js.map
          type: file
        - path: /dist/students/entities/student.entity.d.ts
          type: file
      - path: /dist/students/dto
        type: directory
        contents:
        - path: /dist/students/dto/create-student.dto.js
          type: file
        - path: /dist/students/dto/update-student.dto.js.map
          type: file
        - path: /dist/students/dto/create-student.dto.js.map
          type: file
        - path: /dist/students/dto/update-student.dto.d.ts
          type: file
        - path: /dist/students/dto/create-student.dto.d.ts
          type: file
        - path: /dist/students/dto/update-student.dto.js
          type: file
      - path: /dist/students/students.module.js.map
        type: file
      - path: /dist/students/students.module.d.ts
        type: file
      - path: /dist/students/students.controller.js
        type: file
      - path: /dist/students/students.service.js.map
        type: file
      - path: /dist/students/students.module.js
        type: file
      - path: /dist/students/students.service.d.ts
        type: file
      - path: /dist/students/students.controller.js.map
        type: file
    - path: /dist/main.d.ts
      type: file
    - path: /dist/app.module.d.ts
      type: file
    - path: /dist/core
      type: directory
      contents:
      - path: /dist/core/core.module.js
        type: file
      - path: /dist/core/core.module.d.ts
        type: file
      - path: /dist/core/logger
        type: directory
        contents:
        - path: /dist/core/logger/logger.module.js.map
          type: file
        - path: /dist/core/logger/logger.module.js
          type: file
        - path: /dist/core/logger/logger.module.d.ts
          type: file
      - path: /dist/core/core.module.js.map
        type: file
    - path: /dist/main.js
      type: file
    - path: /dist/app.module.js.map
      type: file
    - path: /dist/main.js.map
      type: file
  - path: /README.md
    type: file
  - path: /package.json
    type: file
  - path: /node_modules
    type: directory
    contents:
    - path: /node_modules/@eslint
      type: directory
      contents:
      - path: /node_modules/@eslint/eslintrc
        type: directory
        contents:
      - path: /node_modules/@eslint/js
        type: directory
        contents:
    - path: /node_modules/@eslint-community
      type: directory
      contents:
      - path: /node_modules/@eslint-community/eslint-utils
        type: directory
        contents:
      - path: /node_modules/@eslint-community/regexpp
        type: directory
        contents:
    - path: /node_modules/ts-jest
      type: directory
      contents:
    - path: /node_modules/eslint-config-prettier
      type: directory
      contents:
    - path: /node_modules/source-map-support
      type: directory
      contents:
    - path: /node_modules/eslint-scope
      type: directory
      contents:
    - path: /node_modules/moment
      type: directory
      contents:
    - path: /node_modules/winston
      type: directory
      contents:
    - path: /node_modules/supertest
      type: directory
      contents:
    - path: /node_modules/prettier-linter-helpers
      type: directory
      contents:
    - path: /node_modules/nest-winston
      type: directory
      contents:
    - path: /node_modules/eslint-plugin-prettier
      type: directory
      contents:
    - path: /node_modules/@nestjs
      type: directory
      contents:
      - path: /node_modules/@nestjs/schematics
        type: directory
        contents:
      - path: /node_modules/@nestjs/cli
        type: directory
        contents:
      - path: /node_modules/@nestjs/testing
        type: directory
        contents:
      - path: /node_modules/@nestjs/mapped-types
        type: directory
        contents:
      - path: /node_modules/@nestjs/platform-express
        type: directory
        contents:
      - path: /node_modules/@nestjs/core
        type: directory
        contents:
      - path: /node_modules/@nestjs/common
        type: directory
        contents:
      - path: /node_modules/@nestjs/config
        type: directory
        contents:
    - path: /node_modules/ts-loader
      type: directory
      contents:
    - path: /node_modules/prettier
      type: directory
      contents:
    - path: /node_modules/@typescript-eslint
      type: directory
      contents:
      - path: /node_modules/@typescript-eslint/utils
        type: directory
        contents:
      - path: /node_modules/@typescript-eslint/parser
        type: directory
        contents:
      - path: /node_modules/@typescript-eslint/eslint-plugin
        type: directory
        contents:
      - path: /node_modules/@typescript-eslint/typescript-estree
        type: directory
        contents:
      - path: /node_modules/@typescript-eslint/types
        type: directory
        contents:
      - path: /node_modules/@typescript-eslint/scope-manager
        type: directory
        contents:
      - path: /node_modules/@typescript-eslint/visitor-keys
        type: directory
        contents:
      - path: /node_modules/@typescript-eslint/type-utils
        type: directory
        contents:
    - path: /node_modules/@types
      type: directory
      contents:
      - path: /node_modules/@types/node
        type: directory
        contents:
      - path: /node_modules/@types/express
        type: directory
        contents:
      - path: /node_modules/@types/supertest
        type: directory
        contents:
      - path: /node_modules/@types/jest
        type: directory
        contents:
    - path: /node_modules/rxjs
      type: directory
      contents:
    - path: /node_modules/typescript
      type: directory
      contents:
    - path: /node_modules/reflect-metadata
      type: directory
      contents:
    - path: /node_modules/typeorm
      type: directory
      contents:
    - path: /node_modules/eslint-visitor-keys
      type: directory
      contents:
    - path: /node_modules/jest
      type: directory
      contents:
    - path: /node_modules/ts-node
      type: directory
      contents:
    - path: /node_modules/tsconfig-paths
      type: directory
      contents:
    - path: /node_modules/eslint
      type: directory
      contents:
  - path: /nest-cli.json
    type: file
  - path: /pnpm-lock.yaml
    type: file
  - path: /src
    type: directory
    contents:
    - path: /src/teachers
      type: directory
      contents:
      - path: /src/teachers/teachers.service.ts
        type: file
      - path: /src/teachers/teachers.module.ts
        type: file
      - path: /src/teachers/teachers.controller.ts
        type: file
      - path: /src/teachers/entities
        type: directory
        contents:
        - path: /src/teachers/entities/teacher.entity.ts
          type: file
      - path: /src/teachers/dto
        type: directory
        contents:
        - path: /src/teachers/dto/create-teacher.dto.ts
          type: file
        - path: /src/teachers/dto/update-teacher.dto.ts
          type: file
      - path: /src/teachers/teachers.controller.spec.ts
        type: file
      - path: /src/teachers/teachers.service.spec.ts
        type: file
    - path: /src/students
      type: directory
      contents:
      - path: /src/students/students.controller.spec.ts
        type: file
      - path: /src/students/students.controller.ts
        type: file
      - path: /src/students/students.module.ts
        type: file
      - path: /src/students/students.service.spec.ts
        type: file
      - path: /src/students/entities
        type: directory
        contents:
        - path: /src/students/entities/student.entity.ts
          type: file
      - path: /src/students/dto
        type: directory
        contents:
        - path: /src/students/dto/update-student.dto.ts
          type: file
        - path: /src/students/dto/create-student.dto.ts
          type: file
      - path: /src/students/students.service.ts
        type: file
    - path: /src/app.module.ts
      type: file
    - path: /src/main.ts
      type: file
    - path: /src/core
      type: directory
      contents:
      - path: /src/core/core.module.ts
        type: file
      - path: /src/core/logger
        type: directory
        contents:
        - path: /src/core/logger/logger.module.ts
          type: file
  - path: /tsconfig.json
    type: file
